### ISSUE TITLE
suite.get() in subscribe() skips the first validation of the field

### ISSUE THREAD

**Issue by codrin-iftimie** [ealush/vest#1157]
```js
const suite = create((data, fields) => {
  // only(fields);
  test("a", "Enter a value", () => {
    enforce(data.a).isNotEmpty();
  });

  test("a", "Enter a value 2", () => {
    enforce(data.a).isNotEmpty();
  });
});

suite.subscribe(() => {
  suite.get();
});

suite({ a: "", b: "" }, ["a"]);
console.log("1", suite.dump());
suite({ a: "", b: "" }, ["a"]);
console.log("2", suite.dump());
```

The first dump **validates the first child** and stops
The second dump **skips the first child** and just does not call the first `.test` for "a" field callback.

Commenting `suite.get();` resolves the issue.
**Note:** subscribe callback is called just the right number of times if `suite.get()` is commented out, else the behavior is unpredictable (called a lot of times returns `{a: ["Enter a value 2"]}` in suite.getErrors()).
https://codesandbox.io/p/sandbox/busy-meadow-q6cw9t

**Comment by ealush** [comment]
Hi!

Thanks for reporting. That sounds unexpected indeed. I will investigate and push a fix.

Thanks!

**Comment by ealush** [comment]
Started looking into this and it definitely looks like a bug. On it.

**Comment by ealush** [comment]
@codrin-iftimie OK. I found the bug. It is very peculiar indeed, and is deeply rooted in how Vest's eager mode works.

The gist of it:

* `subscribe` runs on many events, many of which before your specific test
* Calling suite.get before the test run (regardless of subscribe) builds the internal cache and calculates failing tests
* When running a test, vest's Eager (default) mode checks if we already have failures
* Since we already have the test failing in the previous run - the result would always be "true"
* Vest sees that and skips the test run

That's indeed a bug, and not a pretty one either. The easy solution was to clear the cache before each test run. I am hoping not to see a significant perf hit, if we do - I'll also avoid clearing the cache after each tests. Leaving that bit there for now.

Here's the code change, with the added tests (named after you)

https://github.com/ealush/vest/commit/4854ab262a87f0aa298ee7ad106e80bdab277937

**Comment by ealush** [comment]
I just published vest@5.4.6 which should resolve that. Can you please let me know?

**Comment by codrin-iftimie** [comment]
Thank you for the quick fix. I validated that the fix works, both in a unit test and on the UI.
Thank you again for this awesome library!

**Comment by ealush** [comment]
Amazing! Happy to help
