### ISSUE TITLE
If there are warnings and errors, `classNames` produces only the warning class name

### ISSUE THREAD

**Issue by liady** [ealush/vest#205]
In the React example: 
https://stackblitz.com/edit/vest-react-support-example
If an amount of 1$ is put into the the amount (which is an error - minimum of 2$ is required) - the class is still 'warning' and not 'error' (since it is also a warning - that the amount is less than 10)

**Comment by ealush** [comment]
Hey @liady, thanks for the feedback.
The classNames utility works as expected, as you can see in the screenshot, it adds both the `invalid` class and the `warning` class - as it should.

![image](https://user-images.githubusercontent.com/11255103/85207517-f990b080-b331-11ea-8e31-61e7f0f9c88e.png)

The problem was css precedence - I declared `.warning {}` after `.invalid {}` in `style.scss`, so it was the one that took effect.

Fixed the demo.
