### ISSUE TITLE
isNotEmpty() on date objects

### ISSUE THREAD

**Issue by zeekrey** [ealush/vest#292]
```javascript
 test('date', 'Just testing a date object.', () => {
    enforce(new Date())
      .isNotEmpty()
  });
```

This returns a validation error although `new Date()` is not empty. Seems like the `isNotEmpty()` method only works on strings, arrays and objects. How would you check if a date object exists or even is properly formatted?

Awesome project! Keep up the great work.

**Comment by ealush** [comment]
Hey @zeekrey, thanks for reaching out!

Yes, `isEmpty` and `isNotEmpty` indeed only perform very specific tasks. https://github.com/ealush/vest/blob/latest/packages/n4s/src/rules/isEmpty/index.js, which is not very suitable for checking a date object.

The "empty" Date object that you showed in your code snipped is not empty, since `new Date()` defaults to the current time:

```js
new Date().valueOf()
// -> 1596463051635
```

I believe that what you are looking for is a Date-Object-validity validation rule:

```js
new Date('rr')
// -> Invalid Date

new Date('NaN')
// -> Invalid Date
```

Which can basically be done with `isNaN()`:

```js
isNaN(new Date('x'))
// -> true

isNaN(new Date())
// -> false
```

Which is an actually good rule to have in Vest. I will add it to the next minor version (2.1).

But in the meantime, you can do either of the following:

```js
 // dateObject = new Date('zzz');

 test('date', 'Just testing a date object.', () => {
	return isNaN(dateObject); // Vest treats `false` as test failure
  });

  // See https://ealush.com/vest/#/./test?id=explicitly-returning-false for more info
```

Or, if you want to explicitly use enforce, you can extend enforce to add it locally:

```js
enforce.extend({
    isNaN: (value) => isNaN(value)
});

 // dateObject = new Date('zzz');

 test('date', 'Just testing a date object.', () => {
	enforce(dateObject).isNaN();
  });
```

**Comment by zeekrey** [comment]
Awesome! Thanks for the detailed answer. 😇 I'll go with:

> enforce.extend({
>     isNaN: (value) => isNaN(value)
> });
> 
>  // dateObject = new Date('zzz');
> 
>  test('date', 'Just testing a date object.', () => {
> 	enforce(dateObject).isNaN();
>   });

**Comment by ealush** [comment]
Glad I was able to help 😀
