### ISSUE TITLE
Add support for 'not' prefix for validations

### ISSUE THREAD

**Issue by vligas** [ealush/vest#350]
It would be cool to have something like this: `enforcer(10).not.greaterThan(20)`. this could allow that if you are writing a custom rule you don't have to write also the negative way.

https://jestjs.io/docs/en/expect#not

**Comment by ealush** [comment]
Hey @vligas, that's a good point. I thought about it as well - but the way it is now is intentional - only because I couldn't find a nice intuitive way for consumers to mix `.not` and a chain of rules.

For example, at the moment a consumer can write:

```js
enforce(45).isNumber().greaterThan(10).lessThan(50);
```

Now let's try to chain with a `.not` modifier:

```js
enforce(value).not.isNumber().isEmpty();
```

Now - in the second question, does the `.not` modifier only apply to `.isNumber` or does it apply both to `isNumber` and to `isEmpty`?

Either way we choose, it might confuse the users who think it should be the other way around - unless you can think of an unambiguous way to define it, then I am more than open to add it to the api.

**Comment by vligas** [comment]
mmm ok I see the problem now, the only way that I can think without introducing breaking changes rn is doing something like
```js
enforce(value).not((enf) => enf.isEmpty()).isNumber() 
```
but is a bit verbose 🤔... feel free to close the issue, thx for the explanation @ealush 👌

**Comment by ealush** [comment]
Yes, your solution works, but as you noted, it does not make it easier to write.

Closing this issue for now, might resurface it in the future if we get a better idea.
