### ISSUE TITLE
serial and parallel test support

### ISSUE THREAD

**Issue by zivkaziv** [ealush/vest#427]
The idea is to have the option to run the tests in serially to force those tests not to run parallely.
The idea is from ava framework(https://openbase.io/js/ava-tf/documentation)
By adding `.serial` after the tests you can enforce it 

```js
import vest, { test } from 'vest';
import enforce from 'vest/enforceExtended';

export default vest.create('user_form', (data = {}, currentField) => {
  vest.only(currentField);

  test.serial('username', 'Username is required', () => {
    enforce(data.username).isNotEmpty();
  });

  test.serial('username', 'Username is too short', () => {
    enforce(data.username).longerThanOrEquals(3);
  });

  test.serial('password', 'Password is required', () => {
    enforce(data.password).isNotEmpty();
  });

  test.serial('password', 'Password already used', async () => {
    const response = await axios.post('http://localhost:3000/auth')
    enforce(response.code).matches(/200/);
  });

  if (data.password) {
    test.serial('confirm_password', 'Passwords do not match', () => {
      enforce(data.confirm_password).equals(data.password);
    });
  }

  test.serial('email', 'Email Address is not valid', () => {
    enforce(data.email).isEmail();
  });

  test.serial('tos', () => {
    enforce(data.tos).isTruthy();
  });
});
```

What do you think?

Thanks,
Ziv

**Comment by ealush** [comment]
Hey Ziv, sorry for taking a couple of days to reply.
That's an interesting suggestion. You suggest to have al tests async by default, which could help us with long-operations. I am wondering about the output interface though.

At the moment vest.create returns a function that when run, it returns a result object
```js
const validate = vest.create('name', () => {/*...*/}) // [Function Validate]
const res = validate(data) // [Object object]
res.hasErrors()
res.getErrors()
/*...*/
```

Changing the default to async tests means that the result object will be pretty useless, because it will never have the validation results, unless explicitly `.serial`ed, and in most of the cases, tests are sync.

I am wondering if it would be useful to introduce a parallel mode that would run tests as async by default, unless requested otherwise:

```js
const v = vest.create()
v.async() // run tests as async 
```

Could be interesting to look into.

**Comment by zivkaziv** [comment]
On second thought... I don't have in mind any scenario of running async validation in a parallel.. We can keep this in mind till we have some valid use case:)
