### ISSUE TITLE
TypeScript snafu

### ISSUE THREAD

**Issue by codechips** [ealush/vest#614]
Hey @ealush :wave: 

I think we can all agree that it's super-hard to satisfy the TS compiler. This example code gives me type errors:

```ts
create('Checkout', () => {
  test(
    'coupon',
    'When filled, must be at least 5 chars',
    any(
      () => enforce(data.coupon).isEmpty(),
      () => enforce(data.coupon).longerThanOrEquals(5)
    )
  );
```
![image](https://user-images.githubusercontent.com/44770/116590491-1caaca00-a91e-11eb-89cd-6e0e26aaee6d.png)

However, if I wrap them a function the errors disappear. 

```ts
create('Checkout', () => {
  test(
    'coupon',
    'When filled, must be at least 5 chars', () => {
    any(
      () => { enforce(data.coupon).isEmpty() },
      () => { enforce(data.coupon).longerThanOrEquals(5) }
    )
  });
```
Weird indeed. Have you maybe stumbled on this before? Maybe it something not even TS related?

**Comment by ealush** [comment]
Hm. As much as I hate to admit it, typescript is right this time. I believe this [needs to be fixed in the docs](https://github.com/ealush/vest/blob/79d303df1164c6c9b388564fb7e5ce0474710724/packages/vest/docs/utilities.md#usage).

test [needs to be a function](https://github.com/ealush/vest/blob/79d303df1164c6c9b388564fb7e5ce0474710724/packages/vest/src/core/test/test.js#L100-L102), returning
1. void (undefined)
2. [false](https://github.com/ealush/vest/blob/79d303df1164c6c9b388564fb7e5ce0474710724/packages/vest/src/core/test/test.js#L25-L36)
3. [Promise](https://github.com/ealush/vest/blob/79d303df1164c6c9b388564fb7e5ce0474710724/packages/vest/src/core/test/test.js#L56-L60)

(docs on [how to fail a test](https://ealush.com/vest/#/./test?id=failing-a-test))

While `any` is a function that's when called, [returns a boolean](https://github.com/ealush/vest/blob/79d303df1164c6c9b388564fb7e5ce0474710724/packages/anyone/src/any.js#L8) - so it is like defining a test like this:

```js
create("Checkout", () => {
  test("coupon", "When filled, must be at least 5 chars", false);
});
```

Which is indeed unsupported.
It makes perfect sense why your fix solved it - because it turned it to:

```js
create("Checkout", () => {
  test("coupon", "When filled, must be at least 5 chars", () => false);
});
```
And as explained before - Vest tests do support returning false.

I'll be next to my computer in a few hours to fix it, but feel free to submit a PR if you see this message before I get to it.

That's a really good catch. I am working on a side branch, [re-writing Vest in ts](https://github.com/ealush/vest/compare/2021-04-19-tts) which will make such errors rarer.

**Comment by codechips** [comment]
Thanks for the answer! :bouquet: Closing this
