### ISSUE TITLE
Incorrect paths in typing

### ISSUE THREAD

**Issue by Jefiozie** [ealush/vest#919]
In an exploration of vest in a Angular project I'm seeing several issues with the type information that is provided in the package `n4s`. The error prompted by the compiler is show below and is stating that it cannot find a "module" 

![image](https://user-images.githubusercontent.com/17835373/184010815-c0863597-3d34-40c5-96f8-568a922f03e5.png)

In my exploration to see if I can find the root cause of this issue and if it is related to Angular, I think it is not. As far as I can tell right now is a reference in the typing files of `n4s` wrong and is causing it these issue. When I looked at the typing in the package `n4s` specifically the `n4s.d.ts` file I see that there is a reference made to `packages/vest-utils/types/vest-utils`.  I think this should be a reference to `vest-utils/types/vest-utils` .

Picture below is taken from [unpkg](https://unpkg.com/browse/n4s@4.2.1/types/n4s.d.ts)

![image](https://user-images.githubusercontent.com/17835373/184012190-72f65d66-07b1-48f9-a2e8-6f91c19c7d2c.png)

What I found so far (and I think this is causing the issue but I'm not sure) is that the path mapping in the root `tsconfig.json` file is causing this issue. The typescript compiler will look at the path and use the paths in there for type resolving when generating the types.

I'm happy to assist in any case I can even a PR I'm just not that familiar with the repo itself to make a PR right now. If you could point me in the right directions or need verification I'm happy to assist.

**Comment by ealush** [comment]
Hey @Jefiozie, thank you so much for reporting this. I wouldn't have caught it.

I've been sitting on this for the past four hours, and I seem to have pretty solid grasp of the issue, and I also have a solution in development. The issue is related to what you pointed out, but not quite. During build, I don't use the values from tsConfig as they are - so while it is related, it is not exactly the issue.

I have a solution in mind, but it would still require some work. I published a development version that seems to be working correctly, with one exception:

`import compose from 'vest/enforce/compose'`, `import 'vest/enforce/schema' and `import vest/enforce/compounds` don't work yet. If you need them, you can get all three directly from `n4s` (`import n4s/compose`).

I'd love to hear your feedback on this new version. If it works well for you, I will make sure it covers all exports and release it.

Make sure to have all four installed in order to get the solution working correctly:
n4s@4.2.2-dev-fcaa09
vest-utils@0.0.3-dev-fcaa09
context@3.0.2-dev-fcaa09
vest@4.6.2-dev-fcaa09

**Comment by ealush** [comment]
Also, if you actually want to see the details of this change: https://github.com/ealush/vest/pull/920

**Comment by ealush** [comment]
@Jefiozie, I ran a few more tests, and Vest@4.6.2 seems to fix this issue on my end. Can you try as well?

Here's everything that changed to support this: https://github.com/ealush/vest/commit/4c9f3b83c90a14c430acd728b619dd8c0c669c04

<img width="691" alt="image" src="https://user-images.githubusercontent.com/11255103/184134697-3883189b-ed28-4dd8-b5b3-8f1d5ea0315a.png">

**Comment by Jefiozie** [comment]
Hi, using the dev package I'm seeing a lot more errors then before I'm not sure if this is working as intended. But the `4.6.2` version has resolved my issue, I'm not sure if there is any difference in between them? 

Thank you for resolving this so quickly! I'm looking forward on using your package a bit more then I've had at the moment.
I think we can close down this issue now, thanks @ealush

**Comment by ealush** [comment]
@Jefiozie  Yes, there's quite a difference between the dev version and 4.6.2, especially in terms of the dependency resolution.

I am quite satisfied with the new structure as it makes each package less aware of its surroundings, and only rely on the outfacing api of the other packages.

Again, thank you for reporting this issue and doing the research to find the issue. Glad that it worked for you.
